language: php

php:
  - 7.2

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer validate
  - vendor/bin/phpstan analyse src
  - vendor/bin/phpcs
  - vendor/bin/phpunit -c phpunit.xml

notifications:
    on_success: never
    on_failure: always